# Mi primer cuaderno de ejemplos

In [8]:
print("Hola mundo")

Hola mundo


# Numpy

In [10]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeable
     |████████████████████████████████| 20.1 MB 14.6 MB/s eta 0:00:01
You should consider upgrading via the '/usr/local/bin/python3 -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.


In [1]:
import numpy as np

### Arreglos

In [2]:
arr = np.array([1,2,3])
print(arr)

[1 2 3]


In [4]:
arr = np.array(([1,2,3],[4,5,6]))
print(arr)

[[1 2 3]
 [4 5 6]]


In [5]:
arr = np.array(([1,2,3],[4,5,6],[7,8,9]))
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [8]:
arr = np.array([1,2,3,4,5,6],ndmin=3)
print(arr)
print(arr.ndim)
print(arr[0])
print(arr[0][0])
print(arr[0][0][0])

[[[1 2 3 4 5 6]]]
3
[[1 2 3 4 5 6]]
[1 2 3 4 5 6]
1


In [9]:
arr = np.zeros((2,2))
print(arr)

[[0. 0.]
 [0. 0.]]


In [10]:
arr = np.ones((3,3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [12]:
arr = np.random.rand(3,3)
print(arr)

[[0.92378357 0.22398746 0.24496414]
 [0.56921451 0.6028679  0.19265322]
 [0.16079722 0.95471483 0.06171846]]


### Operaciones

In [13]:
arr1 = [1,2,3]
arr2 = [4,5,6]
arr3 = np.add(arr1,arr2)
print(arr3)

[5 7 9]


In [16]:
arr1 = [1,2,3]
arr2 = [4,5,6]
arr3 = np.subtract(arr2,arr1)
print(arr3)

[3 3 3]


In [17]:
arr1 = [1,2,3]
arr2 = [4,5,6]
arr3 = np.multiply(arr2,arr1)
print(arr3)

[ 4 10 18]


In [18]:
arr1 = [1,2,3]
arr2 = [4,5,6]
arr3 = np.divide(arr2,arr1)
print(arr3)

[4.  2.5 2. ]


### Agregación

In [19]:
arr = [1, 5, 7]
media = np.mean(arr)
print(media)

4.333333333333333


In [20]:
arr = [1, 5, 7]
mediana = np.median(arr)
print(mediana)

5.0


In [21]:
arr = [1, 5, 7]
maximo = np.max(arr)
print(maximo)

7


In [22]:
arr = [1, 5, 7]
minimo = np.min(arr)
print(minimo)

1


### Indexación

In [23]:
arr = np.array([1,2,3,4,5,6])
print(arr[0])

1


In [24]:
arr = np.array([1,2,3,4,5,6])
print(arr[-1])

6


In [26]:
arr = np.array(([1,2,3],[4,5,6]))
print(arr[1,2])

6


### Slicing