# Mi primer cuaderno de ejemplos

In [8]:
print("Hola mundo")

Hola mundo


# Numpy

In [10]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeable
     |████████████████████████████████| 20.1 MB 14.6 MB/s eta 0:00:01
You should consider upgrading via the '/usr/local/bin/python3 -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.


In [1]:
import numpy as np

### Arreglos

In [2]:
arr = np.array([1,2,3])
print(arr)

[1 2 3]


In [4]:
arr = np.array(([1,2,3],[4,5,6]))
print(arr)

[[1 2 3]
 [4 5 6]]


In [5]:
arr = np.array(([1,2,3],[4,5,6],[7,8,9]))
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [8]:
arr = np.array([1,2,3,4,5,6],ndmin=3)
print(arr)
print(arr.ndim)
print(arr[0])
print(arr[0][0])
print(arr[0][0][0])

[[[1 2 3 4 5 6]]]
3
[[1 2 3 4 5 6]]
[1 2 3 4 5 6]
1


In [9]:
arr = np.zeros((2,2))
print(arr)

[[0. 0.]
 [0. 0.]]


In [10]:
arr = np.ones((3,3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [12]:
arr = np.random.rand(3,3)
print(arr)

[[0.92378357 0.22398746 0.24496414]
 [0.56921451 0.6028679  0.19265322]
 [0.16079722 0.95471483 0.06171846]]


### Operaciones

In [13]:
arr1 = [1,2,3]
arr2 = [4,5,6]
arr3 = np.add(arr1,arr2)
print(arr3)

[5 7 9]


In [16]:
arr1 = [1,2,3]
arr2 = [4,5,6]
arr3 = np.subtract(arr2,arr1)
print(arr3)

[3 3 3]


In [17]:
arr1 = [1,2,3]
arr2 = [4,5,6]
arr3 = np.multiply(arr2,arr1)
print(arr3)

[ 4 10 18]


In [18]:
arr1 = [1,2,3]
arr2 = [4,5,6]
arr3 = np.divide(arr2,arr1)
print(arr3)

[4.  2.5 2. ]


### Agregación

In [19]:
arr = [1, 5, 7]
media = np.mean(arr)
print(media)

4.333333333333333


In [20]:
arr = [1, 5, 7]
mediana = np.median(arr)
print(mediana)

5.0


In [21]:
arr = [1, 5, 7]
maximo = np.max(arr)
print(maximo)

7


In [22]:
arr = [1, 5, 7]
minimo = np.min(arr)
print(minimo)

1


### Indexación

In [23]:
arr = np.array([1,2,3,4,5,6])
print(arr[0])

1


In [24]:
arr = np.array([1,2,3,4,5,6])
print(arr[-1])

6


In [26]:
arr = np.array(([1,2,3],[4,5,6]))
print(arr[1,2])

6


### Slicing

In [27]:
arr = np.array([1,2,3,4,5,6])
print(arr[1:4])

[2 3 4]


In [28]:
arr = np.array([1,2,3,4,5,6])
print(arr[1:4:2])

[2 4]


In [29]:
arr = np.array([1,2,3,4,5,6])
print(arr[::2])

[1 3 5]


In [30]:
arr = np.array([1,2,3,4,5,6])
print(arr[::-1])

[6 5 4 3 2 1]


### Tipos de datos

In [3]:
import numpy as np
arr = np.array(['b','a'])
print(arr.dtype)
print(arr)

<U1
['b' 'a']


In [4]:
import numpy as np
arr = np.array([1.1,2.5])
print(arr.dtype)
print(arr)

float64
[1.1 2.5]


In [6]:
import numpy as np
arr = np.array([1,2,3], dtype="S")
print(arr.dtype)
print(arr)

|S1
[b'1' b'2' b'3']


In [8]:

arr = np.array([1.1,2.2,3.3])
print(arr.dtype)
print(arr)
nuevo_arr = arr.astype('i')
print(nuevo_arr.dtype)
print(nuevo_arr)

float64
[1.1 2.2 3.3]
int32
[1 2 3]


In [12]:
# Copy vs View
arr = np.array([1,2,3])
x = arr.copy()
y = arr.view()
print(arr)
print(x)
print(y)
arr[0] = 0
print(arr)
print(x)
print(y)

[1 2 3]
[1 2 3]
[1 2 3]
[0 2 3]
[1 2 3]
[0 2 3]


In [13]:
# Concatenar
arr1 = np.array([1,2,3])
print(arr1)
arr2 = np.array([4,5,6])
print(arr2)
arr3 = np.concatenate((arr1,arr2))
print(arr3)

[1 2 3]
[4 5 6]
[1 2 3 4 5 6]


In [15]:
# Búsqueda
arr = np.array([1,2,3,4,5,5,4])
x = np.where(arr == 4)
print(x)

(array([3, 6]),)


In [17]:
# Ordenar
arr = np.array([1,2,3,4,5,5,4])
a = np.sort(arr)
print(a)

[1 2 3 4 4 5 5]


## Pandas 
#### (para análisis de datos, nos permite analizar estructuras de datos como tablas, hojas de excel, distintos tipos de archivos, mediante dataframes)

In [22]:
pip install pandas


Defaulting to user installation because normal site-packages is not writeable
     |████████████████████████████████| 11.8 MB 2.5 MB/s eta 0:00:01
     |████████████████████████████████| 502 kB 18.4 MB/s eta 0:00:01
     |████████████████████████████████| 341 kB 21.1 MB/s eta 0:00:01
You should consider upgrading via the '/usr/local/bin/python3 -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.


In [23]:
import pandas as pd

In [24]:
# Series
a = np.array([1,2,3])
srs = pd.Series(a)
print(srs)

0    1
1    2
2    3
dtype: int64


In [26]:
srs = pd.Series(a,index = ['x','y','z'])
print(srs)
print(srs['y'])

x    1
y    2
z    3
dtype: int64
2


In [27]:
pasos = {
    'lunes': 440,
    'martes': 634,
    'miercoles': 700,
    'jueves':500,
    'viernes': 150
}
srs = pd.Series(pasos)
print(srs)

lunes        440
martes       634
miercoles    700
jueves       500
viernes      150
dtype: int64


In [28]:
srs = pd.Series(pasos, index = ['lunes','jueves'])
print(srs)

lunes     440
jueves    500
dtype: int64


In [29]:
# DataFrame
mydataset = {
    'operador': ['John Doe','Sr. X','Lorem Ipsum'],
    'no. reloj': [101,202,303]
}
df = pd.DataFrame(mydataset)
print(df)

      operador  no. reloj
0     John Doe        101
1        Sr. X        202
2  Lorem Ipsum        303


In [30]:
df['no. reloj']

0    101
1    202
2    303
Name: no. reloj, dtype: int64

In [32]:
df['operador']

0       John Doe
1          Sr. X
2    Lorem Ipsum
Name: operador, dtype: object

In [33]:
# Podemos filtrar los datos segun una determinada condición:
df[df['no. reloj'] > 101]

operador  no. reloj
1        Sr. X        202
2  Lorem Ipsum        303

In [35]:
# añadiendo nuevas columnas a nuestro dataframe
df['asistencia']=['True','False','True']

In [36]:
print(df)

      operador  no. reloj asistencia
0     John Doe        101       True
1        Sr. X        202      False
2  Lorem Ipsum        303       True


In [37]:
# Traer los datos de un registro (según su indice)
print(df.loc[0])

operador      John Doe
no. reloj          101
asistencia        True
Name: 0, dtype: object


In [39]:
# Igual, pero de un rango de indices
print(df.loc[[0,1]])

   operador  no. reloj asistencia
0  John Doe        101       True
1     Sr. X        202      False


In [40]:
# podemos poner nombres a los indices
df = pd.DataFrame(mydataset, index = ['CEO',"COO","CFO"])
print(df)

        operador  no. reloj
CEO     John Doe        101
COO        Sr. X        202
CFO  Lorem Ipsum        303


In [41]:
print(df.loc['CEO'])

operador     John Doe
no. reloj         101
Name: CEO, dtype: object


In [42]:
print(df.loc[['CEO','COO']])

     operador  no. reloj
CEO  John Doe        101
COO     Sr. X        202


In [49]:
# VISTAS
df = pd.read_csv("Perfil de estudiante.csv")
df

Marca temporal  \
0    2023/06/27 7:42:12 p. m. GMT-6   
1    2023/06/27 7:42:28 p. m. GMT-6   
2    2023/06/27 7:42:44 p. m. GMT-6   
3    2023/06/27 7:42:52 p. m. GMT-6   
4    2023/06/27 7:42:56 p. m. GMT-6   
5    2023/06/27 7:42:57 p. m. GMT-6   
6    2023/06/27 7:42:57 p. m. GMT-6   
7    2023/06/27 7:43:04 p. m. GMT-6   
8    2023/06/27 7:43:10 p. m. GMT-6   
9    2023/06/27 7:43:12 p. m. GMT-6   
10   2023/06/27 7:43:12 p. m. GMT-6   
11   2023/06/27 7:43:16 p. m. GMT-6   
12   2023/06/27 7:43:16 p. m. GMT-6   
13   2023/06/27 7:43:29 p. m. GMT-6   
14   2023/06/27 7:43:34 p. m. GMT-6   
15   2023/06/27 7:43:50 p. m. GMT-6   
16   2023/06/27 7:44:01 p. m. GMT-6   
17   2023/06/27 7:44:01 p. m. GMT-6   
18   2023/06/27 7:44:12 p. m. GMT-6   
19   2023/06/27 7:44:14 p. m. GMT-6   
20   2023/06/27 7:44:17 p. m. GMT-6   
21   2023/06/27 7:44:20 p. m. GMT-6   
22   2023/06/27 7:44:25 p. m. GMT-6   
23   2023/06/27 7:44:30 p. m. GMT-6   
24   2023/06/27 7:44:31 p. m. GMT-6   
25   2023/06/27 7:45:04 p. m. GMT-6   
26   2023/06/27 7:45:37 p. m. GMT-6   
27   2023/06/27 7:45:45 p. m. GMT-6   
28   2023/06/27 7:46:10 p. m. GMT-6   
29   2023/06/27 7:46:14 p. m. GMT-6   
30   2023/06/27 7:46:28 p. m. GMT-6   
31   2023/06/27 7:46:32 p. m. GMT-6   
32   2023/06/27 7:46:37 p. m. GMT-6   
33   2023/06/27 7:49:23 p. m. GMT-6   
34   2023/06/27 7:51:23 p. m. GMT-6   
35   2023/06/27 7:55:00 p. m. GMT-6   
36   2023/06/27 8:05:42 p. m. GMT-6   
37   2023/06/27 8:22:29 p. m. GMT-6   
38  2023/06/27 10:02:11 p. m. GMT-6   
39  2023/06/27 10:31:28 p. m. GMT-6   
40  2023/06/28 10:12:04 p. m. GMT-6   
41   2023/06/29 2:00:51 a. m. GMT-6   
42   2023/07/03 1:55:24 p. m. GMT-6   

                          1.- ¿De dónde eres? 2.- ¿Cuántos años tienes?  \
0                                  Cd. Juárez             Entre 21 y 24   
1                        chihuahua, chihuahua             Entre 21 y 24   
2                         Chihuahua Chihuahua             Entre 18 y 20   
3                         Chihuahua Chihuahua             Entre 21 y 24   
4                            Chihuahua, Chih.                 Más de 30   
5                                      Puebla             Entre 21 y 24   
6                             Cd. Juarez Chih                 Más de 30   
7                               Ciudad Juarez             Entre 21 y 24   
8                              Aguascalientes             Entre 18 y 20   
9                            Cd Juarez, Chih.             Entre 21 y 24   
10                                     Juárez             Entre 21 y 24   
11                                 El Paso TX             Entre 18 y 20   
12                       Cuauhtemoc Chihuahua                 Más de 30   
13                                Cd. Juárez              Entre 21 y 24   
14                                    Hidalgo             Entre 25 y 29   
15                          Cd. Juarez, Chih.             Entre 21 y 24   
16                       Cd. Juarez Chihuahua                 Más de 30   
17             Ciudad Juarez Chihuahua Mexico             Entre 21 y 24   
18                              Ciudad Juarez                 Más de 30   
19                           Chihuahua, Chih.                 Más de 30   
20                              Ciudad Juarez             Entre 18 y 20   
21               Cd Juárez Chihuahua, México.                 Más de 30   
22                              Ciudad Juárez                 Más de 30   
23                                 Cd. Juárez             Entre 25 y 29   
24                                     Juarez             Entre 25 y 29   
25                     Cd. Juárez, Chihuahua              Entre 18 y 20   
26                            Aguascalientes              Entre 21 y 24   
27                                 Cd. Juarez             Entre 15 y 17   
28  San Francisco de los Romo, Aguascalientes             Entre 18 y 20   
29                                  Chihuahua         

In [51]:
# Nos devuelve los primeros 5 regisgtros del DataSet
# (o si queremos un numero diferente, lo ponemos en los parentesis)
df.head(3)

Marca temporal   1.- ¿De dónde eres?  \
0  2023/06/27 7:42:12 p. m. GMT-6            Cd. Juárez   
1  2023/06/27 7:42:28 p. m. GMT-6  chihuahua, chihuahua   
2  2023/06/27 7:42:44 p. m. GMT-6   Chihuahua Chihuahua   

  2.- ¿Cuántos años tienes? 3.- ¿Estudias? 4.- ¿Trabajas?  \
0             Entre 21 y 24             Sí             No   
1             Entre 21 y 24             Sí             Sí   
2             Entre 18 y 20             Sí             Sí   

  5.- ¿Cuál es tu nivel de conocimiento en Python?  \
0                                           Básico   
1                                           Básico   
2                                           Básico   

  6.- ¿Qué tema relacionado con Python te gustaría aprender?  \
0                             Manejar bases de datos           
1                                    machine lerning           
2      Automatización y creación de apps/páginas web           

  7.- ¿Has participado en algún curso anteriormente en el IA Center?  \
0                                                 No                   
1                                                 Sí                   
2                                                 No                   

  8.- ¿Cuál es tu canción favorita?  
0                          The Wolf  
1                   eternity, anyma  
2    Cornerstone- Arctic Monkeys :)

In [45]:
# Nos devuelve los últimos 5 registros
df.tail()

Marca temporal                1.- ¿De dónde eres?  \
38  2023/06/27 10:02:11 p. m. GMT-6                Ciudad Juarez, Chih   
39  2023/06/27 10:31:28 p. m. GMT-6                          cd juarez   
40  2023/06/28 10:12:04 p. m. GMT-6                          Chihuahua   
41   2023/06/29 2:00:51 a. m. GMT-6  Vivo en Ciudad Juárez. Soy cubana   
42   2023/07/03 1:55:24 p. m. GMT-6                      Ciudad Juarez   

   2.- ¿Cuántos años tienes? 3.- ¿Estudias? 4.- ¿Trabajas?  \
38             Entre 21 y 24             No             Sí   
39             Entre 21 y 24             Sí             Sí   
40             Entre 21 y 24             No             Sí   
41                 Más de 30             Sí             No   
42                 Más de 30             No             Sí   

   5.- ¿Cuál es tu nivel de conocimiento en Python?  \
38                                           Básico   
39                                           Básico   
40                                           Básico   
41                                       Intermedio   
42                                       Intermedio   

   6.- ¿Qué tema relacionado con Python te gustaría aprender?  \
38                                  Analisis de datos           
39                                           punteros           
40                   Machine Learning y Deep Learning           
41  Cómo escribir un código de forma profesional, ...           
42                                     Automatizacion           

   7.- ¿Has participado en algún curso anteriormente en el IA Center?  \
38                                                 Sí                   
39                                                 Sí                   
40                                                 Sí                   
41                                                 No                   
42                                                 No                   

                    8.- ¿Cuál es tu canción favorita?  
38                       https://youtu.be/BGVUiMskx_U  
39                             porter guiame quetzal   
40                                            Runaway  
41  Hay varias, pero últimamente escucho mucho "Cu...  
42                              David Bowie - Heroes

In [46]:
# Nos regresa un resumen y/o descripción de nuestro DataSet
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43 entries, 0 to 42
Data columns (total 9 columns):
 #   Column                                                              Non-Null Count  Dtype 
---  ------                                                              --------------  ----- 
 0   Marca temporal                                                      43 non-null     object
 1   1.- ¿De dónde eres?                                                 43 non-null     object
 2   2.- ¿Cuántos años tienes?                                           43 non-null     object
 3   3.- ¿Estudias?                                                      43 non-null     object
 4   4.- ¿Trabajas?                                                      43 non-null     object
 5   5.- ¿Cuál es tu nivel de conocimiento en Python?                    43 non-null     object
 6   6.- ¿Qué tema relacionado con Python te gustaría aprender?          43 non-null     object
 7   7.- ¿Has participado en algún

In [52]:
# CSV
df = pd.read_csv("Perfil de estudiante.csv")
print(df.to_string())

                     Marca temporal                        1.- ¿De dónde eres? 2.- ¿Cuántos años tienes? 3.- ¿Estudias? 4.- ¿Trabajas? 5.- ¿Cuál es tu nivel de conocimiento en Python?                                           6.- ¿Qué tema relacionado con Python te gustaría aprender? 7.- ¿Has participado en algún curso anteriormente en el IA Center?                             8.- ¿Cuál es tu canción favorita?
0    2023/06/27 7:42:12 p. m. GMT-6                                 Cd. Juárez             Entre 21 y 24             Sí             No                                           Básico                                                                               Manejar bases de datos                                                                 No                                                      The Wolf
1    2023/06/27 7:42:28 p. m. GMT-6                       chihuahua, chihuahua             Entre 21 y 24             Sí             Sí                                      

In [54]:
# JSON
df = pd.read_json("dataset.json")

In [55]:
print(df.to_string())

                                                 personas
0      {'nombre': 'Juan', 'edad': 25, 'ciudad': 'Madrid'}
1  {'nombre': 'María', 'edad': 30, 'ciudad': 'Barcelona'}
2   {'nombre': 'Pedro', 'edad': 35, 'ciudad': 'Valencia'}


In [56]:
# Limpieza de datos
data = {
    'Nombre': ['Juan', 'María', 'Pedro', 'Ana', 'Luis'],
    'Edad': [25, 32, None, 42, 28],
    'Fecha': ['31/01/2020', '31/01/2020', None, '31/01/2020', '01/31/2020'],
    'Género': ['M', 'F', None, 'F', 'M'],
    'Ciudad': ['Madrid', None, 'Madrid', 'Valencia', 'Barcelona'],
    'Altura': [175, 163, 180, 158, 170],
    'Peso': [70, None, 80, 60, 75],
    'Ingresos': [50000, 60000, 40000, None, 55000]
}

In [57]:
print(data)

{'Nombre': ['Juan', 'María', 'Pedro', 'Ana', 'Luis'], 'Edad': [25, 32, None, 42, 28], 'Fecha': ['31/01/2020', '31/01/2020', None, '31/01/2020', '01/31/2020'], 'Género': ['M', 'F', None, 'F', 'M'], 'Ciudad': ['Madrid', None, 'Madrid', 'Valencia', 'Barcelona'], 'Altura': [175, 163, 180, 158, 170], 'Peso': [70, None, 80, 60, 75], 'Ingresos': [50000, 60000, 40000, None, 55000]}


In [59]:
df = pd.DataFrame(data)
print(df)

  Nombre  Edad       Fecha Género     Ciudad  Altura  Peso  Ingresos
0   Juan  25.0  31/01/2020      M     Madrid     175  70.0   50000.0
1  María  32.0  31/01/2020      F       None     163   NaN   60000.0
2  Pedro   NaN        None   None     Madrid     180  80.0   40000.0
3    Ana  42.0  31/01/2020      F   Valencia     158  60.0       NaN
4   Luis  28.0  01/31/2020      M  Barcelona     170  75.0   55000.0


In [60]:
# Podemos crear un nuevo DataFrame, 
# eliminando los registros con campos vacíos (None o NaN)
df_sin_vacios = df.dropna()
print(df_sin_vacios.to_string())

  Nombre  Edad       Fecha Género     Ciudad  Altura  Peso  Ingresos
0   Juan  25.0  31/01/2020      M     Madrid     175  70.0   50000.0
4   Luis  28.0  01/31/2020      M  Barcelona     170  75.0   55000.0


In [61]:
df.dropna(inplace=True)
print(df.to_string())

  Nombre  Edad       Fecha Género     Ciudad  Altura  Peso  Ingresos
0   Juan  25.0  31/01/2020      M     Madrid     175  70.0   50000.0
4   Luis  28.0  01/31/2020      M  Barcelona     170  75.0   55000.0


In [62]:
print(df)

  Nombre  Edad       Fecha Género     Ciudad  Altura  Peso  Ingresos
0   Juan  25.0  31/01/2020      M     Madrid     175  70.0   50000.0
4   Luis  28.0  01/31/2020      M  Barcelona     170  75.0   55000.0


In [66]:
df2 = pd.DataFrame(data)
df2.fillna("Sin registro", inplace = True)
print(df2)

  Nombre          Edad         Fecha        Género        Ciudad  Altura  \
0   Juan          25.0    31/01/2020             M        Madrid     175   
1  María          32.0    31/01/2020             F  Sin registro     163   
2  Pedro  Sin registro  Sin registro  Sin registro        Madrid     180   
3    Ana          42.0    31/01/2020             F      Valencia     158   
4   Luis          28.0    01/31/2020             M     Barcelona     170   

           Peso      Ingresos  
0          70.0       50000.0  
1  Sin registro       60000.0  
2          80.0       40000.0  
3          60.0  Sin registro  
4          75.0       55000.0  


In [69]:
df = pd.DataFrame(data)
df["Ingresos"].fillna(0, inplace =True)
print(df)

  Nombre  Edad       Fecha Género     Ciudad  Altura  Peso  Ingresos
0   Juan  25.0  31/01/2020      M     Madrid     175  70.0   50000.0
1  María  32.0  31/01/2020      F       None     163   NaN   60000.0
2  Pedro   NaN        None   None     Madrid     180  80.0   40000.0
3    Ana  42.0  31/01/2020      F   Valencia     158  60.0       0.0
4   Luis  28.0  01/31/2020      M  Barcelona     170  75.0   55000.0


In [70]:
media = df["Ingresos"].mean()
print(media)

41000.0


In [71]:
df["Edad"].fillna(0, inplace =True)
print(df)

  Nombre  Edad       Fecha Género     Ciudad  Altura  Peso  Ingresos
0   Juan  25.0  31/01/2020      M     Madrid     175  70.0   50000.0
1  María  32.0  31/01/2020      F       None     163   NaN   60000.0
2  Pedro   0.0        None   None     Madrid     180  80.0   40000.0
3    Ana  42.0  31/01/2020      F   Valencia     158  60.0       0.0
4   Luis  28.0  01/31/2020      M  Barcelona     170  75.0   55000.0


In [72]:
df["Fecha"].fillna("01/01/1900", inplace =True)
print(df)

  Nombre  Edad       Fecha Género     Ciudad  Altura  Peso  Ingresos
0   Juan  25.0  31/01/2020      M     Madrid     175  70.0   50000.0
1  María  32.0  31/01/2020      F       None     163   NaN   60000.0
2  Pedro   0.0  01/01/1900   None     Madrid     180  80.0   40000.0
3    Ana  42.0  31/01/2020      F   Valencia     158  60.0       0.0
4   Luis  28.0  01/31/2020      M  Barcelona     170  75.0   55000.0


In [73]:
df["Género"].fillna("N", inplace =True)
print(df)

  Nombre  Edad       Fecha Género     Ciudad  Altura  Peso  Ingresos
0   Juan  25.0  31/01/2020      M     Madrid     175  70.0   50000.0
1  María  32.0  31/01/2020      F       None     163   NaN   60000.0
2  Pedro   0.0  01/01/1900      N     Madrid     180  80.0   40000.0
3    Ana  42.0  31/01/2020      F   Valencia     158  60.0       0.0
4   Luis  28.0  01/31/2020      M  Barcelona     170  75.0   55000.0


In [74]:
# Una recomendación sería que en lugar de llenarla
# con cero pusieramos el valor de la media...
df["Peso"].fillna(0.0, inplace =True)
print(df)

  Nombre  Edad       Fecha Género     Ciudad  Altura  Peso  Ingresos
0   Juan  25.0  31/01/2020      M     Madrid     175  70.0   50000.0
1  María  32.0  31/01/2020      F       None     163   0.0   60000.0
2  Pedro   0.0  01/01/1900      N     Madrid     180  80.0   40000.0
3    Ana  42.0  31/01/2020      F   Valencia     158  60.0       0.0
4   Luis  28.0  01/31/2020      M  Barcelona     170  75.0   55000.0


In [75]:
df["Ciudad"].fillna("Desconocida", inplace =True)
print(df)

  Nombre  Edad       Fecha Género       Ciudad  Altura  Peso  Ingresos
0   Juan  25.0  31/01/2020      M       Madrid     175  70.0   50000.0
1  María  32.0  31/01/2020      F  Desconocida     163   0.0   60000.0
2  Pedro   0.0  01/01/1900      N       Madrid     180  80.0   40000.0
3    Ana  42.0  31/01/2020      F     Valencia     158  60.0       0.0
4   Luis  28.0  01/31/2020      M    Barcelona     170  75.0   55000.0


In [76]:
mediana = df["Ingresos"].median()
print(mediana)

50000.0


In [77]:
moda = df["Ingresos"].mode()
print(moda)

0        0.0
1    40000.0
2    50000.0
3    55000.0
4    60000.0
Name: Ingresos, dtype: float64
